apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-boilerplate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-boilerplate
  template:
    metadata:
      labels:
        app: go-boilerplate
    spec:
      containers:
        - name: go-boilerplate
          image: your-docker-image:latest
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_HOST
              value: redis
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: secret